### ISSUE TITLE
error processing files with less

### ISSUE THREAD

**Issue by dchan14** [jeescu/meteor-react-admin-lte#2]
client/lib/base/lib/admin-lte/skins/skin-blue.less:5: Unknown
   import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-black-light.less:5:
   Unknown import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-black.less:5: Unknown
   import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-blue-light.less:5:
   Unknown import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-green-light.less:5:
   Unknown import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-green.less:5: Unknown
   import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-purple-light.less:5:
   Unknown import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-purple.less:5: Unknown
   import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-red-light.less:5:
   Unknown import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-red.less:5: Unknown
   import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-yellow-light.less:5:
   Unknown import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/skins/skin-yellow.less:5: Unknown
   import: ../../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/404_500_errors.less:8:21: variable
   @screen-sm-max is undefined
   client/lib/base/lib/admin-lte/AdminLTE-without-plugins.less:13:
   Unknown import: ../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/AdminLTE.less:13: Unknown import:
   ../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/alerts.less:7:2: .border-radius is
   undefined
   client/lib/base/lib/admin-lte/bootstrap-social.less:11: Unknown
   import: ../bootstrap-less/mixins.less
   client/lib/base/lib/admin-lte/boxes.less:7:17: variable
   @box-border-radius is undefined
   client/lib/base/lib/admin-lte/buttons.less:7:17: variable

**Comment by jeescu** [comment]
Thanks for finding out! I am updating the meteor version of this project. I'll let you know if it is fixed. :+1:

**Comment by jeescu** [comment]
@dchan14, Updated meteor version to 1.4. Check out if the issue still occurs. You can also contribute if you like too. Thanks :)
